# Generated by Django 3.2.7 on 2021-09-27 15:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=10, unique=True)),
                ('priority', models.BooleanField()),
                ('urgent', models.BooleanField()),
                ('scientist_1', models.CharField(max_length=20)),
                ('scientist_2', models.CharField(max_length=20)),
                ('one_hundred_k_project', models.BooleanField(default=False)),
                ('ddd_project', models.BooleanField(default=False)),
                ('nhse', models.BooleanField(default=False)),
                ('nbt', models.BooleanField(default=False)),
                ('referral_reason', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=50)),
                ('date_added', models.DateField()),
                ('submitter', models.CharField(max_length=20)),
                ('on_panelapp', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workbatch_id', models.IntegerField(unique=True)),
                ('test_type', multiselectfield.db.fields.MultiSelectField(choices=[('trio', 'Trio'), ('singleton', 'Singleton'), ('virtual', 'Virutal')], max_length=22)),
                ('test_status', multiselectfield.db.fields.MultiSelectField(choices=[('active', 'Active'), ('hold', 'Hold'), ('complete', 'Complete'), ('failed', 'Failed'), ('analysis_complete', 'Analysis Complete'), ('re_analysis', 'Re-Analysis')], max_length=57)),
                ('test_result', multiselectfield.db.fields.MultiSelectField(choices=[('diag', 'Diagnosis'), ('likely', 'Likely diagnosis'), ('possible', 'Possible diagnosis'), ('no_diag', 'No diagnosis')], max_length=28)),
                ('additional_seqeuncing', models.BooleanField()),
                ('analysis_completion_date', models.DateTimeField()),
                ('analysis_time', models.TimeField()),
                ('average_read_depth', models.IntegerField()),
                ('coverage_20x', models.IntegerField()),
                ('variant_detected_probability', models.FloatField()),
                ('re_analysis_required', models.BooleanField()),
                ('diagnosis_after_reanalysis', models.BooleanField()),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exome_dev.panel')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starlims_id', models.CharField(max_length=9, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('forename', models.CharField(max_length=100)),
                ('sex', multiselectfield.db.fields.MultiSelectField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=19)),
                ('gender', multiselectfield.db.fields.MultiSelectField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], max_length=19)),
                ('nhs_number', models.IntegerField()),
                ('exome_id', models.CharField(max_length=10)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('active', 'Active'), ('on_hold', 'On hold')], max_length=14)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exome_dev.family', to_field='family_id')),
            ],
        ),
        migrations.CreateModel(
            name='Family_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exome_dev.family', to_field='family_id')),
                ('workbatch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exome_dev.test', to_field='workbatch_id')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(null=True)),
                ('submitter', models.CharField(max_length=10, null=True)),
                ('log', models.CharField(max_length=200, null=True)),
                ('starlims_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exome_dev.patient', to_field='starlims_id')),
            ],
        ),
    ]
