# Generated by Django 3.2.7 on 2021-09-27 15:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0002_auto_20210927_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_result',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('diag', 'Diagnosis'), ('likely', 'Likely diagnosis'), ('possible', 'Possible diagnosis'), ('no_diag', 'No diagnosis')], default=False, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('active', 'Active'), ('hold', 'Hold'), ('complete', 'Complete'), ('failed', 'Failed'), ('analysis_complete', 'Analysis Complete'), ('re_analysis', 'Re-Analysis')], default=False, max_length=57, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('trio', 'Trio'), ('singleton', 'Singleton'), ('virtual', 'Virutal')], default=False, max_length=22, null=True),
        ),
    ]
