# Generated by Django 3.2.7 on 2022-01-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0003_auto_20210927_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='panel_id',
        ),
        migrations.DeleteModel(
            name='Family_Test',
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
