# Generated by Django 3.2.7 on 2022-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0005_auto_20220201_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='family_id',
        ),
        migrations.AddField(
            model_name='family',
            name='workbatch_id',
            field=models.ManyToManyField(to='exome_dev.Test'),
        ),
    ]
