# Generated by Django 3.2.7 on 2022-02-02 08:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0006_auto_20220201_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='additional_seqeuncing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='analysis_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='analysis_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='average_read_depth',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='coverage_20x',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='diagnosis_after_reanalysis',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='library_prep_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='re_analysis_required',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_result',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('diag', 'Diagnosis'), ('likely', 'Likely diagnosis'), ('possible', 'Possible diagnosis'), ('no_diag', 'No diagnosis')], default='Logged', max_length=28),
        ),
        migrations.AlterField(
            model_name='test',
            name='variant_detected_probability',
            field=models.FloatField(blank=True),
        ),
    ]
