# Generated by Django 3.2.7 on 2022-02-02 08:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0007_auto_20220202_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_log',
            name='log',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact_log',
            name='log_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact_log',
            name='submitter',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='scientist_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='additional_seqeuncing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='analysis_completion_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='analysis_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='library_prep_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample_received_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample_sent_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_activation_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('logged', 'Logged'), ('active', 'Active'), ('hold', 'Hold'), ('complete', 'Complete'), ('failed', 'Failed'), ('analysis_complete', 'Analysis Complete'), ('re_analysis', 'Re-Analysis')], default=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('trio', 'Trio'), ('singleton', 'Singleton'), ('virtual', 'Virutal')], default=False, max_length=22),
        ),
    ]
