# Generated by Django 3.2.7 on 2022-02-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0014_clinician_firstname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family_Tests',
            new_name='Family_Test',
        ),
    ]
