# Generated by Django 3.2.7 on 2022-02-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0015_rename_family_tests_family_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='workbatch_id',
        ),
    ]
