# Generated by Django 3.2.7 on 2022-02-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0016_remove_test_workbatch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant_test',
            old_name='family_id',
            new_name='family_test_id',
        ),
    ]
