# Generated by Django 3.2.7 on 2022-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exome_dev', '0017_rename_family_id_variant_test_family_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='2022-02-16'),
            preserve_default=False,
        ),
    ]
